stages:
- check
- build
- deploy

pre-commit:
  stage: check
  image: python:3-slim
  before_script:
  - apt-get update
  - apt-get install -y git
  - pip install "pre-commit==2.21.0"
  script:
  - TMP_MSG_FILE="$(mktemp)"
  - git log -1 --pretty=%B > "${TMP_MSG_FILE}"
  - pre-commit run
      --all-files
      --color=always
      --show-diff-on-failure
      --hook-stage commit &&
    pre-commit run
      --all-files
      --color=always
      --show-diff-on-failure
      --hook-stage commit-msg
      --commit-msg-filename "${TMP_MSG_FILE}" &&
    pre-commit run
      --all-files
      --color=always
      --show-diff-on-failure
      --hook-stage post-commit ||
    {
      >&2 echo "pre-commit checks failed. Please consider installing pre-commit";
      >&2 echo "hooks in your local Git clone by running \`make git-hooks-install\`.";
      exit 1;
    }

build:
  stage: build
  image: alpine:latest
  before_script:
  - apk add --no-cache git make
  script:
  - make build
  artifacts:
    paths:
    - src/sysinfo

pages:
  stage: deploy
  image: alpine:latest
  script:
  - mkdir public
  - mv src/sysinfo public/sysinfo_latest
  artifacts:
    paths:
    - public
  only:
  - develop

deploy-to-github:
  stage: deploy
  image: python:3-slim
  variables:
    GIT_STRATEGY: none
  only:
  - master@imeyer/sysinfo
  - develop@imeyer/sysinfo
  - tags@imeyer/sysinfo
  before_script:
  - apt-get update
  - apt-get install -y file git
  - mkdir --mode=700 ~/.ssh/
  - (umask 0377 && echo "${GITHUB_DEPLOY_KEY}" > ~/.ssh/id_rsa
                && echo "github.com ${GITHUB_HOST_KEY}" >> ~/.ssh/known_hosts)
  script:
  - git clone --mirror "${CI_REPOSITORY_URL}" "${CI_PROJECT_NAME}_mirror"
  - cd "${CI_PROJECT_NAME}_mirror";
    git push --mirror "git@github.com:IngoMeyer441/${CI_PROJECT_NAME}.git";
    cd ..
  - if echo "${CI_COMMIT_TAG}" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
      pip install github-binary-upload;
      echo "${GITHUB_ACCESS_TOKEN}" |
        github-binary-upload --user IngoMeyer441 "IngoMeyer441/${CI_PROJECT_NAME}" "${CI_COMMIT_TAG}" src/sysinfo;
    fi

deploy-to-aur:
  stage: deploy
  needs:
  - deploy-to-github
  image: archlinux:base-devel
  only:
  - tags@imeyer/sysinfo
  before_script:
  - pacman -Syu --noconfirm
  - pacman -S --noconfirm --needed git openssh
  - useradd -m deploy
  - sudo -u deploy bash -c "
      git config --global user.name \"AUR updater\" &&
      git config --global user.email \"aur@updater.org\" &&
      mkdir --mode=700 ~/.ssh/ &&
      (
        umask 0377 &&
        echo \"$AUR_PRIVATE_KEY\" > ~/.ssh/id_rsa &&
        echo \"aur.archlinux.org $AUR_HOST_KEY\" >> ~/.ssh/known_hosts
      )
    "
  script:
  - sudo -u deploy bash -c "
      git clone \"ssh://aur@aur.archlinux.org/${CI_PROJECT_NAME}.git\" \"${CI_PROJECT_NAME}-aur\" &&
      cd \"${CI_PROJECT_NAME}-aur\" &&
      sed
        -i
        -e \"/^pkgver=/c\pkgver=\\\"${CI_COMMIT_TAG#v}\\\"\"
        -e \"/^pkgrel=/c\pkgrel=\\\"1\\\"\"
        PKGBUILD &&
      (
        source PKGBUILD;
        curl -o source -L \"\${source[0]}\";
        SHA256SUM=\"\$(sha256sum source | awk '{ print \$1 }')\";
        sed -i \"/^sha256sums=/c\sha256sums=(\\\"\${SHA256SUM}\\\")\" PKGBUILD;
      ) &&
      makepkg --printsrcinfo > .SRCINFO &&
      git commit -a -m \"Update to version ${CI_COMMIT_TAG#v}\" &&
      git push
    "
