default_stages: ['commit']
repos:
# pre-commit repo:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  # general hooks:
  - id: check-added-large-files  # Prevent giant files from being committed
    args: ['--maxkb=5000']
  - id: check-case-conflict  # Check for files with names that would conflict on a case-insensitive filesystems
  - id: check-executables-have-shebangs  # Checks that non-binary executables have a proper shebang
  - id: check-merge-conflict  # Check for files that contain merge conflict strings
  - id: check-symlinks  # Checks for symlinks which do not point to anything
  - id: check-yaml  # Attempts to load all yaml files to verify syntax
  - id: destroyed-symlinks  # Detects symlinks which are changed to regular files
  - id: detect-private-key  # Checks for the existence of private keys
  - id: end-of-file-fixer  # Makes sure files end in a newline and only a newline
  - id: fix-byte-order-marker  # removes UTF-8 byte order marker
  - id: mixed-line-ending  # Replaces or checks mixed line endings
    args: ['--fix=lf']
  - id: trailing-whitespace  # Trims trailing whitespace
# General repos:
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 2.6.2
  hooks:
  - id: editorconfig-checker
    exclude_types: [markdown]
- repo: https://github.com/IngoMeyer441/detect-direct-checkins
  rev: v0.1.2
  hooks:
  - id: detect-direct-checkins
    args: ['--branch=master', '--allow-root']
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.18.0
  hooks:
  - id: gitlint
    args: [
      '--ignore=body-is-missing,title-must-not-contain-word',
      '--msg-filename',
    ]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.33.0
  hooks:
  - id: markdownlint
- repo: https://github.com/adrienverge/yamllint
  rev: v1.29.0
  hooks:
  - id: yamllint
    args: [
      '--config-data={extends: default, rules: {indentation: {indent-sequences: consistent}, line-length: {max: 120}}}'
    ]
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.20.0
  hooks:
  - id: check-jsonschema
    name: 'Validate GitLab CI configuration'
    files: ^\.gitlab-ci.yml
    args: [
      '--schemafile',
      'https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json',
    ]
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.20.0
  hooks:
  - id: check-github-workflows
# Shell specific repos:
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.2
  hooks:
  - id: shellcheck
